### ISSUE TITLE
missing/extra writing systems

### ISSUE THREAD

**Issue by kargaranamir** [google-research/url-nlp#4]
Several writing systems are not included in the list of languages you have, but wikipedia has them. I think that's odd. Did you check Wikipedia for all of them? 

For example, for ["tuk"](https://github.com/google-research/url-nlp/blob/702d8374544b8740838b7db3693750f46fd54aee/language_metadata/data.tsv#L2524), [Wikipedia](https://en.wikipedia.org/wiki/Turkmen_language) says it has a "Perso-Arabic" ("Arab") writing system, but you don't have it in your data.

**Comment by kargaranamir** [comment]
Possible writing systems that you don't have (I will update this list):
- tuk in Arab
- rmy in Cyrillic
- tgk in Latin

**Comment by icaswell** [comment]
Hi! The writing systems in the table are referring only to the script that we have our data in. It is true that many of these languages have alternate writing systems. For the current project, we only got one script per language; future work could extend this.

**Comment by kargaranamir** [comment]
and possible wrong extra writing systems:

Latin in fas
Latin in rus
Latin in kat
